### ISSUE TITLE
User session creation: if user is provided, check and use this user

### ISSUE THREAD

**Issue by mohierf** [IPM-France/applications-backend#11]
Default behavior when posting a new `userservice_session_user` is to add an item, and this item uses the current logged-in user id.

What I would like is: 
- check if the required session status is `open`, if not, refuse the creation

- check if a `user` parameter is provided. If so, use this user instead of the currently logged-in user 

- check if the required session status is `open`, if the user is still linked to this session, do nothing

**Comment by ddurieux** [comment]
Add a hook for that

**Comment by ddurieux** [comment]
If you want deny the POST in the hook, add something like : 
```
abort(make_response("xxx not possible", 412))
```

412 is the HTTP error code, so try to use the right related with problem

**Comment by mohierf** [comment]
Ok for 1st and 3rd problems, but for the second one, how do I change user ?

**Comment by ddurieux** [comment]
example:

```
def pre_contact_post(items):
    """
    Hook before insert.
    When add contact, hash the backend password of the user

    :param items: list of items (list because can use bulk)
    :type items: list
    :return: None
    """
    for index, item in enumerate(items):
        if 'password' in item:
            items[index]['password'] = generate_password_hash(item['password'])
```

**Comment by mohierf** [comment]
Ok, not very difficult indeed :smile:
