### ISSUE TITLE
PATCH Event

### ISSUE THREAD

**Issue by lbarsali** [IPM-France/applications-backend#13]
Avec le User "borne", un PATCH sur un event pour ajouter le champ "result" renvoit le message : 
422
{
  "_status": "ERR",
  "_issues": {
    "result": "unknown field"
  }
}

pour info: 
patcher un event avec un champ existant (par ex. "message") fonctionne avec le User "borne"

**Comment by mohierf** [comment]
J'ai pas mis en prod les derniers commit ... je les installe tout de suite ...

**Comment by mohierf** [comment]
Tu peux refaire le test et me dire STP

**Comment by lbarsali** [comment]
C'est bon, ca marche !
Merci :+1:
