### ISSUE TITLE
Serveur injoignable

### ISSUE THREAD

**Issue by lbarsali** [IPM-France/applications-backend#2]
Le webservice sur http://107.191.47.221:5002 est injoignable (depuis le 21/12 matin).

**Comment by ddurieux** [comment]
C'est relancé ;)

**Comment by lbarsali** [comment]
Merci :+1:

**Comment by lbarsali** [comment]
Hello,
le serveur est encore down ce matin ?

**Comment by ddurieux** [comment]
Non, il tourne la

**Comment by lbarsali** [comment]
ah... je n'arrive plus à m'y connecter... 
Je regarde de mon côté, merci ;)

**Comment by ddurieux** [comment]
Le port est bien accessible? (avec telnet) ?

**Comment by lbarsali** [comment]
le serveur répond sur le port 80 mais plus sur 5002

**Comment by ddurieux** [comment]
désolé, je l'avait relancé sur le mauvais port, la ça devrait être ok

**Comment by lbarsali** [comment]
oui c'est bon, merci !

**Comment by lbarsali** [comment]
Hello
le serveur est apparemment HS (?)
Merci.

**Comment by ddurieux** [comment]
Ah oui j'ai pas relancé après le reboot du serveur, c'est ok maintenant, désolé pour le problème

**Comment by lbarsali** [comment]
Super, merci !

**Comment by lbarsali** [comment]
Hello,
Le serveur vient de tomber HS ...

**Comment by mohierf** [comment]
Je viens de le relancer ... je n'ai pas fait gaffe, mais quand j'ai quitté ma session je ne 'avais pas lancé en background :angry:
