### ISSUE TITLE
POST Json + base64 = 422

### ISSUE THREAD

**Issue by lbarsali** [IPM-France/applications-backend#3]
quand je post un document via /event : 
`{
	"message": "New document from TEST",
	"user": "568bd3d0bc53eb323a89bc77",
	"document": "data:image/png;base64,iVBORw0KGgo etc.....
}`

J'obtiens une erreur 422 : 

`{"_status":"ERR","_issues":{"document":"file was expected, got 'data:image/png;base64,iVBORw0KGgo ... II=' instead."},"_error":{"message":"Insertion failure: 1 document(s) contain(s) error(s)","code":422}}`

Une idée ?
Merci

**Comment by lbarsali** [comment]
Sinon : 
quel moyen aurait-on pour poster un PDF vers le backend ?
 - côté "Conseiller", il est plus probable qu'ils souhaitent envoyer des pdf vers la borne ...
 - côté "Borne", on pourra bientôt disposer d'une API pour convertir un scan en PDF ...

**Comment by ddurieux** [comment]
Je vais ajouter des tests ce weekend / lundi, ca permettra de corriger ou vérifier que l'ajout de document fonctionne, je te tiens au courant

**Comment by mohierf** [comment]
@ddurieux : tu peux refaire un tests dans ce sens STP: post de fichiers vers le serveur ? C'est urgent maintenant cette histoire !

**Comment by lbarsali** [comment]
Effectivement, avec un fichier posté par le biais d'un formulaire, ça fonctionne  : 

![image](https://cloud.githubusercontent.com/assets/6641206/13054201/ba2ca762-d408-11e5-8858-6cd7a3225882.png)

**Comment by lbarsali** [comment]
Un petit up sur ce sujet, car j'ai besoin d'un coup de pouce !

On peut effectivement passer un document via un formulaire...
Mais le cas d'usage sera de passer le document en base64 dans un json : 
        `{
          'user': req.params.user_id,
          'userservice_session': req.params.userservice_session_id,
          'message': 'new document from kiosk '+req.params.kiosk_serial,
          'document': new Buffer(base64data, 'base64')  [ ou new Buffer(data, 'binary') ]
        }`

Or, on récupère en retour une erreur 422, car 'document' est une String et non un File...
(la valeur 'data' provient d'un readFile NodeJs qui renvoit un objet Buffer)

Pourrait-on faire en sorte que le format attendu par 'document' soit une string et non en fichier ?

**Comment by lbarsali** [comment]
P2 : pas indispensable pour le moment...

**Comment by ddurieux** [comment]
Je ne suis pas sur que tu envoi dans le bon format, cf http://python-eve.org/features.html#file-storage

Je vais jeter un oeil
