### ISSUE TITLE
Echange de document

### ISSUE THREAD

**Issue by lbarsali** [IPM-France/applications-backend#4]
Il pourrait être intéressant de bénéficier d'un objet Document qui contiendrait par ex. : 
- "id": "xxx"
- "title": "yyy"
- "href": "document/zzz.pdf",
Le href permettrait d'afficher directement ce document dans un navigateur.

Dans ce cas de figure, utiliserait-on toujours les events pour poster un nouveau document ?

**Comment by ddurieux** [comment]
On peut rajouter dans le event : title (default='') et href (default='')

**Comment by mohierf** [comment]
Modifications réalisées dans le backend pour gérer les transferts de documents.
