### ISSUE TITLE
Compte utilisateur

### ISSUE THREAD

**Issue by lbarsali** [IPM-France/applications-backend#5]
On utilise toujours 'admin' / 'admin' pour se connecter au backend...
Pourrait-on avoir un compte utilisateur 'kiosk' avec des droits ouverts pour la création de users, services, sessions, events, etc. ?

**Comment by ddurieux** [comment]
Normalement, tu dois pouvoir créer un nouvel utilisateur sur le /user (un POST sur /user) avec : 
```
{name: 'toto', password: '123456', is_admin: True}
```
