### ISSUE TITLE
table USER vide !

### ISSUE THREAD

**Issue by lbarsali** [IPM-France/applications-backend#6]
je crois que j'ai fait une boulette : j'ai fait un delete sur /user au lieu de /user/id !!
désolé : tu pourrais recréer un user admin ??

merci

**Comment by ddurieux** [comment]
Je viens de le relancer, normalement ça a dû le recréer, tu peux tester et me dire si c'est ok?

**Comment by lbarsali** [comment]
C'est nickel ! Merci :)
